/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lopez.julz;

import db.DCRSummaryTransactionsDao;
import db.DatabaseConnection;
import db.PaidBillDetailsDao;
import db.PaidBillsDao;
import db.TransactionDetailsDao;
import db.TransactionIndexDao;
import helpers.ConfigFileHelpers;
import helpers.Notifiers;
import helpers.ObjectHelpers;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import pojos.DCRSummaryTransactions;
import pojos.PaidBills;
import pojos.Server;
import pojos.TransactionDetails;

/**
 *
 * @author Julio Lopez
 */
public class DCRPanel extends javax.swing.JPanel {
    public pojos.Login login;
    
    public Server server;
    public String office;
    
    public DatabaseConnection db;
    public Connection connection;

    public List<DCRSummaryTransactions> dcrSummary;
    public DefaultTableModel dcrSummaryModel;
    public Object[] dcrSummaryColNames = {"GL Code", "Description", "Amount"};
    
    public List<PaidBills> powerBills;
    public DefaultTableModel powerBillsModel;
    public Object[] powerBillsColNames = {"OR Number", "OR Date", "Account No", "Consumer Name", "Billing Mo", "Payment Time", "Kwh Used", "2%", "5%", "Surcharges", "OCL", "Deductions", "Amount Due"};
    
    public List<TransactionDetails> nonPowerBills;
    public DefaultTableModel nonPowerBillsModel;
    public Object[] nonPowerBillsColNames = {"OR Number", "Payee Name", "GL Code", "Particulars", "Amount Paid"};
    
    public List<TransactionDetails> checkPayments;
    public DefaultTableModel checkPaymentsModel;
    public Object[] checkPaymentsColNames = {"OR Number", "Account No", "Payee Name", "Check No", "Bank", "Amount", "Source"};
   
    public DCRPanel(pojos.Login login) {
        this.login = login;
        initComponents();
        
        server = ConfigFileHelpers.getServer();
        office = ConfigFileHelpers.getOffice();
    
        db = new DatabaseConnection();
        connection = db.getDbConnectionFromDatabase(server);
        
        dcrSummary = new ArrayList<>();
        powerBills = new ArrayList<>();
        nonPowerBills = new ArrayList<>();
        checkPayments = new ArrayList<>();
        
        dcrDate.getFormattedTextField().setValue(Calendar.getInstance());
        dcrDate.getFormattedTextField().setFont(new Font("Arial", Font.BOLD, 13));
        
        getAllDCR();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dcrDate = new org.jdatepicker.JDatePicker();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        goBtnDcr = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dcrSummaryTab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        totalDcrSummaryLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dcrSummaryTable = new javax.swing.JTable();
        powerBillsTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        powerBillsTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        powerBillsTable = new javax.swing.JTable();
        nonPowerBillsTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nonPowerBillsTotalLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nonPowerBillsTable = new javax.swing.JTable();
        checkPaymentsTab = new javax.swing.JPanel();
        checkPaymentsTotalLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        checkTable = new javax.swing.JTable();
        cancelledOrsTab = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/request_quote_FILL1_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel1.setText("Daily Collection Report");
        jLabel1.setIconTextGap(10);

        dcrDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel2.setText("Select Date");

        goBtnDcr.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        goBtnDcr.setText("Go");
        goBtnDcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnDcrActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        jLabel3.setText("Total  :  ");

        totalDcrSummaryLabel.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        totalDcrSummaryLabel.setForeground(new java.awt.Color(204, 51, 0));
        totalDcrSummaryLabel.setText("0.0");

        dcrSummaryTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dcrSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dcrSummaryTable);

        javax.swing.GroupLayout dcrSummaryTabLayout = new javax.swing.GroupLayout(dcrSummaryTab);
        dcrSummaryTab.setLayout(dcrSummaryTabLayout);
        dcrSummaryTabLayout.setHorizontalGroup(
            dcrSummaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dcrSummaryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dcrSummaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
                    .addGroup(dcrSummaryTabLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(totalDcrSummaryLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dcrSummaryTabLayout.setVerticalGroup(
            dcrSummaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dcrSummaryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dcrSummaryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalDcrSummaryLabel))
                .addContainerGap())
        );

        jTabbedPane1.addTab("DCR Summary", dcrSummaryTab);

        powerBillsTab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        jLabel4.setText("Total  :  ");

        powerBillsTotal.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        powerBillsTotal.setForeground(new java.awt.Color(204, 51, 0));
        powerBillsTotal.setText("0.0");

        powerBillsTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        powerBillsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(powerBillsTable);

        javax.swing.GroupLayout powerBillsTabLayout = new javax.swing.GroupLayout(powerBillsTab);
        powerBillsTab.setLayout(powerBillsTabLayout);
        powerBillsTabLayout.setHorizontalGroup(
            powerBillsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(powerBillsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(powerBillsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
                    .addGroup(powerBillsTabLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(powerBillsTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        powerBillsTabLayout.setVerticalGroup(
            powerBillsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, powerBillsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(powerBillsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(powerBillsTotal))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Power Bills Payments", powerBillsTab);

        nonPowerBillsTab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        jLabel5.setText("Total  :  ");

        nonPowerBillsTotalLabel.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        nonPowerBillsTotalLabel.setForeground(new java.awt.Color(204, 51, 0));
        nonPowerBillsTotalLabel.setText("0.0");

        nonPowerBillsTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nonPowerBillsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(nonPowerBillsTable);

        javax.swing.GroupLayout nonPowerBillsTabLayout = new javax.swing.GroupLayout(nonPowerBillsTab);
        nonPowerBillsTab.setLayout(nonPowerBillsTabLayout);
        nonPowerBillsTabLayout.setHorizontalGroup(
            nonPowerBillsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nonPowerBillsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nonPowerBillsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
                    .addGroup(nonPowerBillsTabLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(nonPowerBillsTotalLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nonPowerBillsTabLayout.setVerticalGroup(
            nonPowerBillsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nonPowerBillsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(nonPowerBillsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nonPowerBillsTotalLabel))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Non-Power Bills Payments", nonPowerBillsTab);

        checkPaymentsTotalLabel.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        checkPaymentsTotalLabel.setForeground(new java.awt.Color(204, 51, 0));
        checkPaymentsTotalLabel.setText("0.0");

        jLabel6.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        jLabel6.setText("Total  :  ");

        checkTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        checkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(checkTable);

        javax.swing.GroupLayout checkPaymentsTabLayout = new javax.swing.GroupLayout(checkPaymentsTab);
        checkPaymentsTab.setLayout(checkPaymentsTabLayout);
        checkPaymentsTabLayout.setHorizontalGroup(
            checkPaymentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPaymentsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkPaymentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
                    .addGroup(checkPaymentsTabLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(checkPaymentsTotalLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        checkPaymentsTabLayout.setVerticalGroup(
            checkPaymentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkPaymentsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(checkPaymentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkPaymentsTotalLabel))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Check Payments", checkPaymentsTab);

        javax.swing.GroupLayout cancelledOrsTabLayout = new javax.swing.GroupLayout(cancelledOrsTab);
        cancelledOrsTab.setLayout(cancelledOrsTabLayout);
        cancelledOrsTabLayout.setHorizontalGroup(
            cancelledOrsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
        );
        cancelledOrsTabLayout.setVerticalGroup(
            cancelledOrsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cancelled ORs", cancelledOrsTab);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Print DCR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcrDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goBtnDcr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(goBtnDcr)
                        .addComponent(dcrDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBtnDcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnDcrActionPerformed
        getAllDCR();
    }//GEN-LAST:event_goBtnDcrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelledOrsTab;
    private javax.swing.JPanel checkPaymentsTab;
    private javax.swing.JLabel checkPaymentsTotalLabel;
    private javax.swing.JTable checkTable;
    private org.jdatepicker.JDatePicker dcrDate;
    private javax.swing.JPanel dcrSummaryTab;
    private javax.swing.JTable dcrSummaryTable;
    private javax.swing.JButton goBtnDcr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel nonPowerBillsTab;
    private javax.swing.JTable nonPowerBillsTable;
    private javax.swing.JLabel nonPowerBillsTotalLabel;
    private javax.swing.JPanel powerBillsTab;
    private javax.swing.JTable powerBillsTable;
    private javax.swing.JLabel powerBillsTotal;
    private javax.swing.JLabel totalDcrSummaryLabel;
    // End of variables declaration//GEN-END:variables

    public void getAllDCR() {
        getDcrSummary();
        getPowerBills();
        getNonPowerBills();
        getCheckPayments();
    }
    
    public void getDcrSummary() {
        try {
            dcrSummary.clear();
            if (dcrSummaryModel != null) {
                dcrSummaryModel.getDataVector().removeAllElements();
                dcrSummaryModel.fireTableDataChanged();
            }
            
            dcrSummary.addAll(DCRSummaryTransactionsDao.getDcrSummary(connection, ObjectHelpers.formatSqlDate(dcrDate.getFormattedTextField().getText()), login.getId()));
            int dcrSize = dcrSummary.size();
            double dcrSummaryTotal = 0;
            Object[][] data = new Object[dcrSize][dcrSummaryColNames.length];
            int tbIndex = 0;
            for (int i=0; i<dcrSize; i++) {
                if (dcrSummary.get(i).getAmount() != null && Double.valueOf(dcrSummary.get(i).getAmount()) != 0) {
                    data[tbIndex][0] = dcrSummary.get(i).getGLCode();
                    data[tbIndex][1] = dcrSummary.get(i).getDescription();
                    data[tbIndex][2] = ObjectHelpers.roundTwo(dcrSummary.get(i).getAmount());
                    dcrSummaryTotal += Double.valueOf(dcrSummary.get(i).getAmount());
                    tbIndex++;
                }                    
            }
            dcrSummaryModel = new DefaultTableModel(data, dcrSummaryColNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }                
            };
            DefaultTableCellRenderer rightRendererBlue = new DefaultTableCellRenderer();
            rightRendererBlue.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererBlue.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererBlue.setForeground(Color.BLUE);
            
            dcrSummaryTable.setModel(dcrSummaryModel);
            dcrSummaryTable.setRowHeight(28);
            dcrSummaryTable.getColumnModel().getColumn(0).setMaxWidth(120);
            dcrSummaryTable.getColumnModel().getColumn(0).setMinWidth(110);
            dcrSummaryTable.getColumnModel().getColumn(2).setMaxWidth(150);
            dcrSummaryTable.getColumnModel().getColumn(2).setMinWidth(110);
            dcrSummaryTable.getColumnModel().getColumn(2).setCellRenderer(rightRendererBlue);
            dcrSummaryTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            
            totalDcrSummaryLabel.setText(ObjectHelpers.roundTwo(dcrSummaryTotal + ""));
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Getting Summary Transactions", e.getMessage());
        }
    }

    public void getPowerBills() {
        try {
            powerBills.clear();
            if (powerBillsModel != null) {
                powerBillsModel.getDataVector().removeAllElements();
                powerBillsModel.fireTableDataChanged();
            }
            
            powerBills.addAll(PaidBillsDao.getCashPowerBills(connection, ObjectHelpers.formatSqlDate(dcrDate.getFormattedTextField().getText()), login.getId()));
            int powerBillsSize = powerBills.size();
            double powerBillsTotal = 0;
            Object[][] data = new Object[powerBillsSize][powerBillsColNames.length];
            for (int i=0; i<powerBillsSize; i++) {
                data[i][0] = powerBills.get(i).getORNumber();
                data[i][1] = powerBills.get(i).getORDate();
                data[i][2] = powerBills.get(i).getAccountNumber();
                data[i][3] = powerBills.get(i).getId(); // CONSUMER NAME
                data[i][4] = powerBills.get(i).getServicePeriod();
                data[i][5] = powerBills.get(i).getPostingTime();
                data[i][6] = powerBills.get(i).getKwhUsed();
                data[i][7] = powerBills.get(i).getForm2307TwoPercent() != null ? ObjectHelpers.roundTwo(powerBills.get(i).getForm2307TwoPercent()) : "0";
                data[i][8] = powerBills.get(i).getForm2307FivePercent() != null ? ObjectHelpers.roundTwo(powerBills.get(i).getForm2307FivePercent()) : "0";
                data[i][9] = powerBills.get(i).getSurcharge() != null ? ObjectHelpers.roundTwo(powerBills.get(i).getSurcharge()) : "0";
                data[i][10] = powerBills.get(i).getAdditionalCharges() != null ? ObjectHelpers.roundTwo(powerBills.get(i).getAdditionalCharges()) : "0";
                data[i][11] = powerBills.get(i).getDeductions() != null ? ObjectHelpers.roundTwo(powerBills.get(i).getDeductions()) : "0";
                data[i][12] = powerBills.get(i).getNetAmount() != null ? ObjectHelpers.roundTwo(powerBills.get(i).getNetAmount()) : "0";
                powerBillsTotal += Double.valueOf(powerBills.get(i).getNetAmount());                  
            }
            powerBillsModel = new DefaultTableModel(data, powerBillsColNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }                
            };
            
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
            
            DefaultTableCellRenderer rightRendererBlue = new DefaultTableCellRenderer();
            rightRendererBlue.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererBlue.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererBlue.setForeground(Color.BLUE);
            
            DefaultTableCellRenderer rightRendererTeal = new DefaultTableCellRenderer();
            rightRendererTeal.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererTeal.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererTeal.setForeground(Color.decode("#009688"));
            
            DefaultTableCellRenderer rightRendererRed = new DefaultTableCellRenderer();
            rightRendererRed.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererRed.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererRed.setForeground(Color.decode("#d32f2f"));
            
            powerBillsTable.setModel(powerBillsModel);
            powerBillsTable.setRowHeight(28);
            powerBillsTable.getColumnModel().getColumn(0).setMaxWidth(60);
            powerBillsTable.getColumnModel().getColumn(0).setMinWidth(50);
            powerBillsTable.getColumnModel().getColumn(1).setMaxWidth(100);
            powerBillsTable.getColumnModel().getColumn(1).setMinWidth(70);
            powerBillsTable.getColumnModel().getColumn(2).setMaxWidth(110);
            powerBillsTable.getColumnModel().getColumn(2).setMinWidth(90);
            powerBillsTable.getColumnModel().getColumn(4).setMaxWidth(100);
            powerBillsTable.getColumnModel().getColumn(4).setMinWidth(70);
            powerBillsTable.getColumnModel().getColumn(5).setMaxWidth(100);
            powerBillsTable.getColumnModel().getColumn(5).setMinWidth(80);
            powerBillsTable.getColumnModel().getColumn(6).setMaxWidth(60);
            powerBillsTable.getColumnModel().getColumn(6).setMinWidth(40);
            powerBillsTable.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
            powerBillsTable.getColumnModel().getColumn(7).setMaxWidth(70);
            powerBillsTable.getColumnModel().getColumn(7).setMinWidth(50);
            powerBillsTable.getColumnModel().getColumn(7).setCellRenderer(rightRendererTeal);
            powerBillsTable.getColumnModel().getColumn(8).setMaxWidth(70);
            powerBillsTable.getColumnModel().getColumn(8).setMinWidth(50);
            powerBillsTable.getColumnModel().getColumn(8).setCellRenderer(rightRendererTeal);
            powerBillsTable.getColumnModel().getColumn(9).setMaxWidth(80);
            powerBillsTable.getColumnModel().getColumn(9).setMinWidth(60);
            powerBillsTable.getColumnModel().getColumn(9).setCellRenderer(rightRendererRed);
            powerBillsTable.getColumnModel().getColumn(10).setMaxWidth(90);
            powerBillsTable.getColumnModel().getColumn(10).setMinWidth(60);
            powerBillsTable.getColumnModel().getColumn(10).setCellRenderer(rightRendererRed);
            powerBillsTable.getColumnModel().getColumn(11).setMaxWidth(90);
            powerBillsTable.getColumnModel().getColumn(11).setMinWidth(60);
            powerBillsTable.getColumnModel().getColumn(11).setCellRenderer(rightRendererTeal);
            powerBillsTable.getColumnModel().getColumn(12).setMaxWidth(130);
            powerBillsTable.getColumnModel().getColumn(12).setMinWidth(100);
            powerBillsTable.getColumnModel().getColumn(12).setCellRenderer(rightRendererBlue);
            powerBillsTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
            
            this.powerBillsTotal.setText("(" + powerBillsSize + ") " + ObjectHelpers.roundTwo(powerBillsTotal + ""));
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Getting Power Bills", e.getMessage());
        }
    }
    
    public void getNonPowerBills() {
        try {
            nonPowerBills.clear();
            if (nonPowerBillsModel != null) {
                nonPowerBillsModel.getDataVector().removeAllElements();
                nonPowerBillsModel.fireTableDataChanged();
            }
            
            nonPowerBills.addAll(TransactionIndexDao.getDcr(connection, ObjectHelpers.formatSqlDate(dcrDate.getFormattedTextField().getText()), login.getId()));
            int npbSize = nonPowerBills.size();
            double nonPowerBillsTotal = 0;
            Object[][] data = new Object[npbSize][nonPowerBillsColNames.length];
            String prevHolder = "", prev = "";
            for (int i=0; i<npbSize; i++) {
                prevHolder = nonPowerBills.get(i).getId();
                data[i][0] = prevHolder.equals(prev) ? "" : nonPowerBills.get(i).getId();
                data[i][1] = prevHolder.equals(prev) ? "" : nonPowerBills.get(i).getVAT();
                data[i][2] = nonPowerBills.get(i).getAccountCode();
                data[i][3] = nonPowerBills.get(i).getParticular();
                data[i][4] = ObjectHelpers.roundTwo(nonPowerBills.get(i).getTotal());
                nonPowerBillsTotal += Double.valueOf(nonPowerBills.get(i).getTotal());   
                prev = prevHolder;                
            }
            nonPowerBillsModel = new DefaultTableModel(data, nonPowerBillsColNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }                
            };
            
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
            
            DefaultTableCellRenderer rightRendererBlue = new DefaultTableCellRenderer();
            rightRendererBlue.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererBlue.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererBlue.setForeground(Color.BLUE);
            
            DefaultTableCellRenderer rightRendererTeal = new DefaultTableCellRenderer();
            rightRendererTeal.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererTeal.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererTeal.setForeground(Color.decode("#009688"));
            
            DefaultTableCellRenderer rightRendererRed = new DefaultTableCellRenderer();
            rightRendererRed.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererRed.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererRed.setForeground(Color.decode("#d32f2f"));
            
            nonPowerBillsTable.setModel(nonPowerBillsModel);
            nonPowerBillsTable.setRowHeight(28);
            nonPowerBillsTable.getColumnModel().getColumn(0).setMaxWidth(60);
            nonPowerBillsTable.getColumnModel().getColumn(0).setMinWidth(50);
            nonPowerBillsTable.getColumnModel().getColumn(2).setMaxWidth(120);
            nonPowerBillsTable.getColumnModel().getColumn(2).setMinWidth(100);
            nonPowerBillsTable.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
            nonPowerBillsTable.getColumnModel().getColumn(4).setMaxWidth(130);
            nonPowerBillsTable.getColumnModel().getColumn(4).setMinWidth(100);
            nonPowerBillsTable.getColumnModel().getColumn(4).setCellRenderer(rightRendererBlue);
            
            nonPowerBillsTotalLabel.setText("(" + npbSize + ") " + ObjectHelpers.roundTwo(nonPowerBillsTotal + ""));
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Getting Non-Power Bills", e.getMessage());
        }
    }
    
    public void getCheckPayments() {
        try {
            checkPayments.clear();
            if (checkPaymentsModel != null) {
                checkPaymentsModel.getDataVector().removeAllElements();
                checkPaymentsModel.fireTableDataChanged();
            }
            
            checkPayments.addAll(DCRSummaryTransactionsDao.getCheckPayments(connection, ObjectHelpers.formatSqlDate(dcrDate.getFormattedTextField().getText()), login.getId()));
            int checkSize = checkPayments.size();
            double checkPaymentsTotal = 0;
            Object[][] data = new Object[checkSize][checkPaymentsColNames.length];
            String prevHolder = "", prev = "";
            for (int i=0; i<checkSize; i++) {
                data[i][0] = checkPayments.get(i).getId(); // OR NUMBER
                data[i][1] = checkPayments.get(i).getTransactionIndexId(); // ACCOUNT NUMBER
                data[i][2] = checkPayments.get(i).getParticular(); // PAYEE NAME/ACCOUNT NAME
                data[i][3] = checkPayments.get(i).getVAT(); // CHECK NO
                data[i][4] = checkPayments.get(i).getAccountCode(); // BANK
                data[i][5] = ObjectHelpers.roundTwo(checkPayments.get(i).getTotal());
                data[i][6] = checkPayments.get(i).getAmount();
                checkPaymentsTotal += Double.valueOf(checkPayments.get(i).getTotal());   
                prev = prevHolder;                
            }
            checkPaymentsModel = new DefaultTableModel(data, checkPaymentsColNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }                
            };
            
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
            
            DefaultTableCellRenderer rightRendererBlue = new DefaultTableCellRenderer();
            rightRendererBlue.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererBlue.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererBlue.setForeground(Color.BLUE);
            
            DefaultTableCellRenderer rightRendererTeal = new DefaultTableCellRenderer();
            rightRendererTeal.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererTeal.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererTeal.setForeground(Color.decode("#009688"));
            
            DefaultTableCellRenderer rightRendererRed = new DefaultTableCellRenderer();
            rightRendererRed.setHorizontalAlignment(JLabel.RIGHT);
            rightRendererRed.setFont(new Font("Arial", Font.BOLD, 12));
            rightRendererRed.setForeground(Color.decode("#d32f2f"));
            
            checkTable.setModel(checkPaymentsModel);
            checkTable.setRowHeight(28);
            checkTable.getColumnModel().getColumn(0).setMaxWidth(60);
            checkTable.getColumnModel().getColumn(0).setMinWidth(50);
            checkTable.getColumnModel().getColumn(1).setMaxWidth(130);
            checkTable.getColumnModel().getColumn(1).setMinWidth(120);
            checkTable.getColumnModel().getColumn(3).setMaxWidth(200);
            checkTable.getColumnModel().getColumn(3).setMinWidth(180);
            checkTable.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            checkTable.getColumnModel().getColumn(4).setMaxWidth(130);
            checkTable.getColumnModel().getColumn(4).setMinWidth(100);
            checkTable.getColumnModel().getColumn(5).setMaxWidth(180);
            checkTable.getColumnModel().getColumn(5).setMinWidth(150);
            checkTable.getColumnModel().getColumn(5).setCellRenderer(rightRendererBlue);
            checkTable.getColumnModel().getColumn(6).setMaxWidth(180);
            checkTable.getColumnModel().getColumn(6).setMinWidth(150);
            
            checkPaymentsTotalLabel.setText("(" + checkSize + ") " + ObjectHelpers.roundTwo(checkPaymentsTotal + ""));
        } catch (Exception e) {
            e.printStackTrace();
            Notifiers.showErrorMessage("Error Getting Check Payments", e.getMessage());
        }
    }
}
